![image](https://user-images.githubusercontent.com/80379900/113644294-6c032f00-96bf-11eb-8b17-9cac39b141c6.png)
> 데이터에 남아있는 찌꺼기 값이 호출되서 num2가 제대로 리턴되는 것처럼 보이나
> 이후 난수가 들어있는 걸 볼 수 있다.
